# Generated by Django 5.0.2 on 2024-12-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='batch_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='middle_name',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
    ]
