# Generated by Django 5.0.2 on 2024-12-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_alumni_batch_year_alter_alumni_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
