# Generated by Django 5.0.2 on 2024-12-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alter_alumni_batch_year_alter_alumni_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='user',
        ),
    ]
